name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - intel-openmp=2021.4.0
  - jupyterlab_widgets=1.0.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - pip=22.2.2
  - plotly=5.9.0
  - python=3.9.13
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tenacity=8.0.1
  - wheel=0.37.1
  - pip:
    - altair==4.2.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.5
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - commonmark==0.9.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - einops==0.5.0
    - entrypoints==0.4
    - executing==1.1.1
    - fancy-einsum==0.0.3
    - fastjsonschema==2.16.2
    - gitdb==4.0.9
    - gitpython==3.1.29
    - idna==3.4
    - importlib-metadata==5.0.0
    - ipykernel==6.16.0
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - jupyter-client==7.4.2
    - jupyter-core==4.11.1
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.1
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.1
    - notebook-shim==0.1.0
    - packaging==21.3
    - pandas==1.5.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.31
    - protobuf==3.20.3
    - psutil==5.9.2
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pycparser==2.21
    - pydeck==0.8.0b4
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==24.0.1
    - requests==2.28.1
    - rich==12.6.0
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - streamlit==1.13.0
    - terminado==0.16.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.12.1
    - torchvision==0.13.1
    - tornado==6.2
    - traitlets==5.4.0
    - typing-extensions==4.4.0
    - tzdata==2022.5
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - widgetsnbextension==3.4.2
    - zipp==3.9.0
